FROM arm64v8/ubuntu:20.04@sha256:ca83774d06420ceb4682ef73bd9cbbfc38a97a27e061b578547a6761206658b9

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud Ubuntu" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/ubuntu" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/ubuntu" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/ubuntu"

ENV DEBIAN_FRONTEND noninteractive
ENV TERM xterm

ADD https://github.com/owncloud-ci/wait-for/releases/download/v1.0.2/wait-for-linux-arm64 /usr/bin/wait-for

ENV SU_EXEC_CHECKSUM=73244a858f5514a927a0f2510d533b4b57169b64d2aa3f9d98d92a7a7df80cea
ADD https://github.com/tianon/gosu/releases/download/1.14/gosu-arm64 /usr/bin/su-exec

ENV GOMPLATE_CHECKSUM=c0363592eb1f70d6ab3c5451a8dd319fbf5e23fdd0f0e3ea2b05ef6013c38540
ADD https://github.com/hairyhenderson/gomplate/releases/download/v3.10.0/gomplate_linux-arm64 /usr/bin/gomplate

RUN chmod +x /usr/bin/wait-for && \
  echo "${SU_EXEC_CHECKSUM} /usr/bin/su-exec" | sha256sum -c - && \
  chmod +x /usr/bin/su-exec && \
  echo "${GOMPLATE_CHECKSUM} /usr/bin/gomplate" | sha256sum -c - && \
  chmod +x /usr/bin/gomplate

RUN apt-get update -y && \
  apt-get install -y \
    ca-certificates \
    bash \
    vim \
    curl \
    wget \
    rsync \
    procps \
    apt-utils \
    apt-transport-https \
    iputils-ping \
    bzip2 \
    unzip \
    cron \
    git-core \
    sshpass \
    tree \
    jq \
    gnupg \
    libnss-wrapper && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY ./overlay /
CMD ["bash"]
