FROM docker.io/ubuntu:22.04@sha256:e6173d4dc55e76b87c4af8db8821b1feae4146dd47341e4d431118c7dd060a74

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud Ubuntu" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/ubuntu" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/ubuntu" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/ubuntu"

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

ENV DEBIAN_FRONTEND noninteractive
ENV TERM xterm

# renovate: datasource=github-releases depName=hairyhenderson/gomplate
ENV GOMPLATE_VERSION="${GOMPLATE_VERSION:-v3.11.6}"
# renovate: datasource=github-releases depName=owncloud-ci/wait-for
ENV WAIT_FOR_VERSION="${WAIT_FOR_VERSION:-v2.0.1}"
# renovate: datasource=github-releases depName=owncloud-ci/retry
ENV RETRY_VERSION="${RETRY_VERSION:-v2.0.0}"

RUN apt-get update -y && \
  apt-get install --no-install-recommends -y \
    ca-certificates \
    bash \
    curl \
    wget \
    procps \
    apt-utils \
    apt-transport-https \
    bzip2 \
    cron \
    jq \
    gnupg \
    libnss-wrapper && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl -SsfL -o /usr/bin/gomplate "https://github.com/hairyhenderson/gomplate/releases/download/${GOMPLATE_VERSION}/gomplate_${TARGETOS}-${TARGETARCH}${TARGETVARIANT}" && \
    curl -SsfL -o /usr/bin/wait-for "https://github.com/owncloud-ci/wait-for/releases/download/${WAIT_FOR_VERSION}/wait-for-${TARGETOS}-${TARGETARCH}${TARGETVARIANT}" && \
    curl -SsfL -o /usr/bin/retry "https://github.com/owncloud-ci/retry/releases/download/${RETRY_VERSION}/retry" && \
    chmod 755 /usr/bin/gomplate && \
    chmod 755 /usr/bin/wait-for && \
    chmod 755 /usr/bin/retry

ADD overlay /
CMD ["bash"]
