FROM arm32v7/ubuntu:16.10@sha256:9859098f8fbef03472cb0e42a6339d4754ad83cc91acbb769b7f39c8a1f5d47e as build

RUN apt-get update && apt-get install -y wget

ENV GOMPLATE_DOWNLOAD=https://github.com/hairyhenderson/gomplate/releases/download/v3.0.0/gomplate_linux-arm-slim
ENV GOMPLATE_CHECKSUM=fb9bf19fb8e42aac690f724a3252bd5fe62322d620a8a1b1cb4308f6b684381c

RUN cd /tmp && \
  wget -O gomplate ${GOMPLATE_DOWNLOAD} && \
  echo "${GOMPLATE_CHECKSUM} *gomplate" | sha256sum -c - && \
  chmod +x gomplate

ENV SU_EXEC_DOWNLOAD=https://github.com/tianon/gosu/releases/download/1.11/gosu-armhf
ENV SU_EXEC_CHECKSUM=171b4a2decc920de0dd4f49278d3e14712da5fa48de57c556f99bcdabe03552e

RUN cd /tmp && \
  wget -O su-exec ${SU_EXEC_DOWNLOAD} && \
  echo "${SU_EXEC_CHECKSUM} *su-exec" | sha256sum -c - && \
  chmod +x su-exec

FROM arm32v7/golang:1.13 as golang

ENV CGO_ENABLED=0
ENV WAIT_FOR_REPO=https://github.com/alioygur/wait-for
ENV WAIT_FOR_COMMIT=a2569b146c861c574e62d416699b78efe66ed883

RUN git clone ${WAIT_FOR_REPO} /go/wait-for && \
  cd /go/wait-for && \
  git checkout ${WAIT_FOR_COMMIT} && \
  go build -v -a -installsuffix cgo -o /tmp/wait-for

FROM arm32v7/ubuntu:16.10@sha256:9859098f8fbef03472cb0e42a6339d4754ad83cc91acbb769b7f39c8a1f5d47e

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>" \
  org.label-schema.name="ownCloud Ubuntu" \
  org.label-schema.vendor="ownCloud GmbH" \
  org.label-schema.schema-version="1.0"

ENV DEBIAN_FRONTEND noninteractive
ENV TERM xterm

RUN apt-get update -y && \
  apt-get upgrade -y && \
  apt-get install -y \
    ca-certificates \
    bash \
    vim \
    curl \
    wget \
    procps \
    apt-utils \
    apt-transport-https \
    iputils-ping \
    bzip2 \
    unzip \
    cron \
    git-core \
    sshpass \
    tree \
    gnupg && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY ./overlay /
CMD ["bash"]

COPY --from=build /tmp/gomplate /usr/bin/gomplate
COPY --from=build /tmp/su-exec /usr/bin/su-exec
COPY --from=golang /tmp/wait-for /usr/bin/wait-for
