FROM arm32v7/ubuntu:18.04@sha256:ec5715e4fd292b212edd9062c1abe247298ed3acf87b9555b55cc9b16e7f628a

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud Ubuntu" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/ubuntu" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/ubuntu" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/ubuntu"

ENV DEBIAN_FRONTEND noninteractive
ENV TERM xterm

ADD https://github.com/owncloud-ci/wait-for/releases/download/v1.0.2/wait-for-linux-arm /usr/bin/wait-for

ENV SU_EXEC_CHECKSUM=abb1489357358b443789571d52b5410258ddaca525ee7ac3ba0dd91d34484589
ADD https://github.com/tianon/gosu/releases/download/1.14/gosu-armhf /usr/bin/su-exec

ENV GOMPLATE_CHECKSUM=b97f60ba85d23b14b8b502a9eb229f9131ecdd7cd3b095b915520b6d3bff7b6e
ADD https://github.com/hairyhenderson/gomplate/releases/download/v3.10.0/gomplate_linux-armv7 /usr/bin/gomplate

RUN chmod +x /usr/bin/wait-for && \
  echo "${SU_EXEC_CHECKSUM} /usr/bin/su-exec" | sha256sum -c - && \
  chmod +x /usr/bin/su-exec && \
  echo "${GOMPLATE_CHECKSUM} /usr/bin/gomplate" | sha256sum -c - && \
  chmod +x /usr/bin/gomplate

RUN apt-get update -y && \
  apt-get install -y \
    ca-certificates \
    bash \
    vim \
    curl \
    wget \
    rsync \
    procps \
    apt-utils \
    apt-transport-https \
    iputils-ping \
    bzip2 \
    unzip \
    cron \
    git-core \
    sshpass \
    tree \
    jq \
    gnupg \
    libnss-wrapper && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY ./overlay /
CMD ["bash"]
