FROM ubuntu:18.04@sha256:a0271b192f9e682a45fcd6026dedcd5d729df312271d629db4fba6cfe8f242bd

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud Ubuntu" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/ubuntu" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/ubuntu" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/ubuntu"

ENV DEBIAN_FRONTEND noninteractive
ENV TERM xterm

ADD https://github.com/owncloud-ci/wait-for/releases/download/v1.0.2/wait-for-linux-amd64 /usr/bin/wait-for

ENV SU_EXEC_CHECKSUM=0f25a21cf64e58078057adc78f38705163c1d564a959ff30a891c31917011a54
ADD https://github.com/tianon/gosu/releases/download/1.12/gosu-amd64 /usr/bin/su-exec

ENV GOMPLATE_CHECKSUM=7dbabe30095f822ec38f5f70711ff121c26e588227da4cc05208417cfaf929cd
ADD https://github.com/hairyhenderson/gomplate/releases/download/v3.9.0/gomplate_linux-amd64 /usr/bin/gomplate

RUN chmod +x /usr/bin/wait-for && \
  echo "${SU_EXEC_CHECKSUM} /usr/bin/su-exec" | sha256sum -c - && \
  chmod +x /usr/bin/su-exec && \
  echo "${GOMPLATE_CHECKSUM} /usr/bin/gomplate" | sha256sum -c - && \
  chmod +x /usr/bin/gomplate

RUN apt-get update -y && \
  apt-get install -y \
    ca-certificates \
    bash \
    vim \
    curl \
    wget \
    procps \
    apt-utils \
    apt-transport-https \
    iputils-ping \
    bzip2 \
    unzip \
    cron \
    git-core \
    sshpass \
    tree \
    jq \
    gnupg \
    libnss-wrapper && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY ./overlay /
CMD ["bash"]
