name: Docker CI

on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
  schedule:
    - cron: 0 0 * * 0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: editorconfig-checker/action-editorconfig-checker@840e866d93b8e032123c23bac69dece044d4d84c

      - run: editorconfig-checker

  build:
    needs: lint
    uses: ./.github/workflows/docker-build.yml
    with:
      docker-repo-name: owncloud/${{ github.event.repository.name }}
      docker-tag: ${{ matrix.version.value }}
      docker-context: v${{ matrix.version.value }}
      docker-file: v${{ matrix.version.value }}/Dockerfile.multiarch
      docker-hub-username: ${{ vars.DOCKERHUB_USERNAME }}
      push: ${{ github.ref == 'refs/heads/master' }}
    secrets:
      docker-hub-password: ${{ secrets.DOCKERHUB_TOKEN }}

    strategy:
      matrix:
        version:
          - value: "24.04"
          - value: "22.04"
          - value: "20.04"

  update-docker-hub-description:
    needs: build
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/docker-hub-desc.yml
    with:
      docker-repo-name: owncloud/${{ github.event.repository.name }}
      docker-repo-description: ownCloud Ubuntu base image
      docker-hub-username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      docker-hub-password: ${{ secrets.DOCKERHUB_TOKEN }}
